export type Language = "en" | "it";

const translations = {
  // ─── Sidebar ───
  "sidebar.dashboard": { en: "Dashboard", it: "Dashboard" },
  "sidebar.exploreAi": { en: "Explore AI", it: "Esplora AI" },
  "sidebar.attribution": { en: "Attribution", it: "Attribuzione" },
  "sidebar.analytics": { en: "Analytics", it: "Analisi" },
  "sidebar.abTests": { en: "A/B Tests", it: "Test A/B" },
  "sidebar.heatmaps": { en: "Heatmaps", it: "Mappe di calore" },
  "sidebar.projects": { en: "Projects", it: "Progetti" },
  "sidebar.landingAnalysis": { en: "Landing Analysis", it: "Analisi Landing" },
  "sidebar.competitorMonitoring": { en: "Competitor Monitoring", it: "Monitoraggio Competitor" },
  "sidebar.archive": { en: "Archive", it: "Archivio" },
  "sidebar.dataSources": { en: "Data Sources", it: "Sorgenti Dati" },
  "sidebar.darkMode": { en: "Dark Mode", it: "Modalità Scura" },
  "sidebar.lightMode": { en: "Light Mode", it: "Modalità Chiara" },
  "sidebar.signOut": { en: "Sign Out", it: "Esci" },
  "sidebar.online": { en: "Online", it: "Online" },
  "sidebar.loading": { en: "Loading...", it: "Caricamento..." },

  // ─── Dashboard / CRO Analysis Studio ───
  "dashboard.title": { en: "CRO Analysis Studio", it: "Studio Analisi CRO" },
  "dashboard.subtitle": {
    en: "Upload a screenshot and get a detailed CRO audit powered by Gemini + GPT + Claude",
    it: "Carica uno screenshot e ottieni un audit CRO dettagliato con Gemini + GPT + Claude",
  },
  "dashboard.dropHere": { en: "Drop your screenshot here", it: "Trascina il tuo screenshot qui" },
  "dashboard.orClick": { en: "or click to browse — PNG, JPG, WebP", it: "o clicca per selezionare — PNG, JPG, WebP" },
  "dashboard.chooseFile": { en: "Choose File", it: "Scegli File" },
  "dashboard.context": { en: "Context (optional)", it: "Contesto (opzionale)" },
  "dashboard.contextPlaceholder": {
    en: "e.g., This is my checkout page for concealed permit application. I'm seeing 40% cart abandonment...",
    it: "es., Questa è la mia pagina checkout per richiesta permesso. Ho un 40% di abbandono carrello...",
  },
  "dashboard.aiPipeline": { en: "AI Pipeline", it: "Pipeline AI" },
  "dashboard.visualAnalysis": { en: "Visual Analysis", it: "Analisi Visiva" },
  "dashboard.tableGeneration": { en: "Table Generation", it: "Generazione Tabella" },
  "dashboard.expertReview": { en: "Expert Review", it: "Revisione Esperta" },
  "dashboard.startAnalysis": { en: "Start CRO Analysis", it: "Avvia Analisi CRO" },
  "dashboard.analyzingWith": { en: "Analyzing with", it: "Analisi con" },
  "dashboard.geminiRaw": { en: "Gemini — Raw Visual Analysis", it: "Gemini — Analisi Visiva Dettagliata" },
  "dashboard.geminiRawDesc": {
    en: "Detailed element-by-element breakdown",
    it: "Analisi dettagliata elemento per elemento",
  },
  "dashboard.croTable": { en: "CRO Comparison Table", it: "Tabella Comparativa CRO" },
  "dashboard.issuesFound": { en: "issues found", it: "problemi trovati" },
  "dashboard.generatedBy": {
    en: "Generated by GPT, reviewed by Claude",
    it: "Generata da GPT, revisionata da Claude",
  },
  "dashboard.totalIssues": { en: "total issues identified", it: "problemi totali identificati" },
  "dashboard.claudeReview": { en: "Claude Review", it: "Revisione Claude" },
  "dashboard.additionalIssues": {
    en: "Additional Issues Found by Claude",
    it: "Problemi Aggiuntivi Trovati da Claude",
  },
  "dashboard.missedBy": {
    en: "missed by primary analysis",
    it: "mancati dall'analisi primaria",
  },
  "dashboard.claudeVerdict": { en: "Claude — Final Verdict", it: "Claude — Verdetto Finale" },
  "dashboard.claudeVerdictDesc": {
    en: "Expert review summary and top priorities",
    it: "Riepilogo revisione esperta e priorità principali",
  },
  "dashboard.upgrade": { en: "Upgrade", it: "Miglioramento" },

  // ─── Table Headers ───
  "table.area": { en: "Area", it: "Area" },
  "table.problem": { en: "❌ Problem", it: "❌ Problema" },
  "table.impact": { en: "🎯 Impact", it: "🎯 Impatto" },
  "table.whyReduces": {
    en: "🧠 Why it reduces conversion",
    it: "🧠 Perché riduce conversione",
  },
  "table.action": { en: "✅ Action to take", it: "✅ Azione da fare" },

  // ─── Header / Breadcrumbs ───
  "header.dashboard": { en: "Dashboard", it: "Dashboard" },

  // ─── Common ───
  "common.comingSoon": { en: "Coming soon", it: "In arrivo" },
  "common.language": { en: "Language", it: "Lingua" },
  "common.english": { en: "EN", it: "EN" },
  "common.italian": { en: "IT", it: "IT" },
} as const;

export type TranslationKey = keyof typeof translations;

export function t(key: TranslationKey, lang: Language): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[lang] || entry.en;
}

export default translations;
